### ISSUE TITLE
您好，我同样使用了Prisma来进行数据库的操作依旧是遇到了博客中提到的问题。

### ISSUE THREAD

**Issue by Xing-YaoLei** [Term-inator/Schedule#5]
您好，我最近也在用Prisma 以及 electron-vite来做一个PC软件的开发。
但是在进行打包的时候遇到了《A JavaScript error occurred in the main process -> Error: Cannot find module '.prisma/client/default' ''》的错误。 

按照[文档](https://cn.electron-vite.org/guide/troubleshooting#%E5%88%86%E5%8F%91)中的方式进行了操作，但是还是没有解决，然后尝试寻找方案的时候朋友推了您的博客帖子找到了您当前的项目。

参考您的项目进行了一定程度的修改，但是发现打包依旧是出现这个问题，所以想要请教一下具体的操作步骤等内容。

**Comment by Term-inator** [comment]
您好，可以查看这个[项目](https://github.com/Term-inator/electron-vue3ts-prisma-template)

**Comment by Xing-YaoLei** [comment]
> 您好，可以查看这个[项目](https://github.com/Term-inator/electron-vue3ts-prisma-template)

这个项目在我的Mac(arm M1)上面安装的时候会报错`npm ERR! RequestError: certificate has expired` 

尝试降级nodejs版本到16版本依旧存在，然后我尝试换了一个windows电脑 运行的时候是不报错的，但是在打包的时候会报错，不知道是不是因为梯子问题。

方不方便加大佬您一个联系方式请教您一下。

**Comment by Term-inator** [comment]
> > 您好，可以查看这个[项目](https://github.com/Term-inator/electron-vue3ts-prisma-template)
> 
> 这个项目在我的Mac(arm M1)上面安装的时候会报错`npm ERR! RequestError: certificate has expired`
> 
> 尝试降级nodejs版本到16版本依旧存在，然后我尝试换了一个windows电脑 运行的时候是不报错的，但是在打包的时候会报错，不知道是不是因为梯子问题。
> 
> 方不方便加大佬您一个联系方式请教您一下。

Mac 上的 npm 是不是使用了镜像源？
Windows 上打包报什么错？
我的 node 版本：20.10.0
微信：zhongjiezhe2001
